"""Private acquisition seam used by the education-resource job runner."""

from .models import (
    ACQUISITION_STRATEGIES,
    CAPABILITY_SCOPES,
    ARTIFACT_ROLES,
    ASSET_ROLES,
    CapabilityScope,
    CompletionKind,
    FORMAL_ARTIFACT_ROLES,
    INTERNAL_ARTIFACT_ROLES,
    MAX_ARTIFACTS,
    PERSISTENT_ARTIFACT_ROLES,
    AcquisitionFailure,
    AcquisitionItemFailure,
    AcquisitionRequest,
    AcquisitionResult,
    AcquisitionStrategy,
    Artifact,
    ArtifactBundle,
    ArtifactRole,
    PreferredContainer,
    StrategyKind,
)
from ..downloader import DownloadBatchResult, DownloadItemFailure, DownloadResult
from .router import (
    AcquisitionRouter,
    BrowserCapture,
    DirectProvider,
    ProviderRegistration,
    WebMaterializer,
)

__all__ = [
    "ACQUISITION_STRATEGIES",
    "CAPABILITY_SCOPES",
    "ARTIFACT_ROLES",
    "ASSET_ROLES",
    "CapabilityScope",
    "CompletionKind",
    "FORMAL_ARTIFACT_ROLES",
    "INTERNAL_ARTIFACT_ROLES",
    "MAX_ARTIFACTS",
    "PERSISTENT_ARTIFACT_ROLES",
    "AcquisitionFailure",
    "AcquisitionItemFailure",
    "AcquisitionRequest",
    "AcquisitionResult",
    "AcquisitionRouter",
    "AcquisitionStrategy",
    "Artifact",
    "ArtifactBundle",
    "ArtifactRole",
    "BrowserCapture",
    "DirectProvider",
    "DownloadBatchResult",
    "DownloadItemFailure",
    "DownloadResult",
    "PreferredContainer",
    "ProviderRegistration",
    "StrategyKind",
    "WebMaterializer",
]
